#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

x = [1,2]
s = 0
while s >= 0:
    s = x[-1] + x[-2]
    if s < 4000000:
        x.append(s)
    else:
        break

t = 0
#print (x , len(x))
for i in range (0, len(x)) :
    if x[i] % 2 == 0:
        t += x[i]

print(t)
